name: CMake

on:
  push:
    branches: [ "feature_1" ]
  pull_request:
    branches: [ "feature_1" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B ${{github.workspace}}/build 

    - name: build main executable
      run: cmake --build ${{github.workspace}}/build --target labwork5 -j 12
      
    - name: build tests
      run: cmake --build ${{github.workspace}}/build --target argparser_tests -j 12
      
    - name: run tests
      working-directory: ${{github.workspace}}/build/tests/Debug/
      run: ./argparser_tests.exe
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with: 
        name: Executable file
        path: ${{github.workspace}}/build/labwork5
    

